### PR TITLE
Adding Grunt Server Task and Refactor Distribution Folder

### PR DESCRIPTION
**Pull request by qwo**

### CODE REVIEW

**Comment by qwo** [comment]
sorry how ugly this PR looks. thanks @wbprice

**Comment by wbprice** [comment]
Uh, some stuff broke.  Where's the Stanley button?

**Comment by qwo** [comment]
let me wam that button for you

**Comment by wbprice** [comment]
Changes from #88 weren't included.  Fixed by running 'grunt' task.  Will push change directly shortly.

**Pull request merged**
