### PR TITLE
Don't show Angular template while loading page

### PR DESCRIPTION
**Pull request by bschoenfeld**
Using ng-cloak (https://docs.angularjs.org/api/ng/directive/ngCloak)

### CODE REVIEW

**Comment by bschoenfeld** [comment]
Wow. Where have I been, huh?

**Comment by wbprice** [comment]
We miss seeing you around.  Can't have the Ben show without Ben!

**Comment by bschoenfeld** [comment]
I miss being around. Obviously, the Ben show is dead and the c4hrva show has taken it's place.

**Comment by qwo** [comment]
:+1:

**Pull request merged**
