### PR TITLE
Improvements to map usability

### PR DESCRIPTION
**Pull request by jspaetzel**
- removed extra poi map data. An example of this; when zoomed into an area it would display a point of interest marker and the custom marker, resulting in many cases of establishments with multiple markers
- moved the zoom and panning controls so that they are not cut off at the top of the page
- removed street view control which does not seem relevant to this application
- indentations -> spaces

### CODE REVIEW

**Comment by wbprice** [comment]
@zzbomb are you going to be at Google I/O again today?  This is looking good, but I want to show you how to setup and use grunt for this project.

**Comment by qwo** [comment]
yeah the angular/grunt setup is weird @zzbomb, production.js is where the gruntfile aggregates and compiles all of .js files together and is automatically generated.

there is an equivalent in another js file in the /js directory

Good Pull Request though! :thumbsup:

**Comment by jspaetzel** [comment]
Oh weird, yes please show me. I'll be over there in an hour or two.

**Comment by qwo** [comment]
yeah :+1: you guys should get here for the giveaways/google wear hack session

**Pull request merged**
