### PR TITLE
Trying to use OpenStreetMap.

### PR DESCRIPTION
**Pull request by ghost**
Probably doing this incorrectly, but trying it anyway.

### CODE REVIEW

**Comment by ghost** [comment]
I tried this for #116.

**Comment by qwo** [comment]
I'm guessing this is related to #116. Have you tested this locally?

The only issue I maybe worrie about is a dependency is ng-maps an angular
specific directive for handling google maps and that might have the same
api effects.

Also it seems like you only updated production.js it would be squashed in
next grunt build

On Thursday, July 10, 2014, Ryan Y. notifications@github.com wrote:

> ## Probably doing this incorrectly, but trying it anyway.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/ryayak1460/open-health-inspection-app gh-pages
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/c4hrva/open-health-inspection-app/pull/117
> Commit Summary
> - Trying to use OpenStreetMap.
> 
> File Changes
> - _M_ js/production.js
>   https://github.com/c4hrva/open-health-inspection-app/pull/117/files#diff-0
>   (27)
> 
> Patch Links:
> - https://github.com/c4hrva/open-health-inspection-app/pull/117.patch
> - https://github.com/c4hrva/open-health-inspection-app/pull/117.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/pull/117.
> 
> ---
> 
> Spam
> https://www.spamtrap.odu.edu/canit/b.php?i=03MoEbEoI&m=b121fb0b253c&t=20140710&c=s
> Not spam
> https://www.spamtrap.odu.edu/canit/b.php?i=03MoEbEoI&m=b121fb0b253c&t=20140710&c=n
> Forget previous vote
> https://www.spamtrap.odu.edu/canit/b.php?i=03MoEbEoI&m=b121fb0b253c&t=20140710&c=f

## 

Stanley Zheng
@stanzheng http://twitter.com/stanzheng

**Comment by wbprice** [comment]
Let's hold off on making any big changes until next Hack Night.

**Comment by qwo** [comment]
agreed with wbprice :+1:

**Comment by ghost** [comment]
@stanzheng Like I said, probably did it wrong.  :laughing: I don't know Angular enough to go about modifying the current code, but those changes in the right place should help get the tiles set up and everything.  Having issues running it at the moment anyway, `grunt server` comes up with nothing.

@wbprice No problem.

**Comment by ghost** [comment]
Tested locally, does not work, closing.

**Pull request closed without merging**
