### PR TITLE
VA Geofence

### PR DESCRIPTION
**Pull request by wbprice**
If someone from outside the state bounds (as defined broadly by Wikipedia) visits the site, they'll get an error message and the coordianates will fall back to Hatch.  Geosearch will continue from there.

### CODE REVIEW

**Comment by jalbertbowden** [comment]
i think we should take a field trip to test this out ;)

**Comment by wbprice** [comment]
I didn't write the logic correctly the first time around, so I rolled the live site back.  Wouldn't object to road trip in principle.

**Comment by jalbertbowden** [comment]
nor i sir....the question is, where are we going?

**Comment by wbprice** [comment]
Triangle Area maybe.

**Comment by jalbertbowden** [comment]
i was not aware raleigh-durham-chapel hill was outside of the us. or do you mean bermuda triangle?

**Pull request merged**
